/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Saurav
 */
public class managedata extends javax.swing.JFrame {
    private Object m41;
    private Object m42;
    private Object m43;
    private Object m44;

    /**
     * Creates new form managedata
     */
    public managedata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        s3 = new javax.swing.JTextField();
        n4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        s2 = new javax.swing.JTextField();
        v1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        s4 = new javax.swing.JTextField();
        n1 = new javax.swing.JTextField();
        n3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        aa3 = new javax.swing.JTextField();
        aa4 = new javax.swing.JTextField();
        at3 = new javax.swing.JTextField();
        an4 = new javax.swing.JTextField();
        at4 = new javax.swing.JTextField();
        an1 = new javax.swing.JTextField();
        at1 = new javax.swing.JTextField();
        an3 = new javax.swing.JTextField();
        aa2 = new javax.swing.JTextField();
        aa1 = new javax.swing.JTextField();
        an2 = new javax.swing.JTextField();
        at2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        ad1 = new javax.swing.JTextField();
        ad2 = new javax.swing.JTextField();
        ad3 = new javax.swing.JTextField();
        ad4 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        m11 = new javax.swing.JTextField();
        m34 = new javax.swing.JTextField();
        mn2 = new javax.swing.JTextField();
        m22 = new javax.swing.JTextField();
        m23 = new javax.swing.JTextField();
        m21 = new javax.swing.JTextField();
        mn4 = new javax.swing.JTextField();
        m24 = new javax.swing.JTextField();
        m13 = new javax.swing.JTextField();
        m31 = new javax.swing.JTextField();
        m32 = new javax.swing.JTextField();
        m33 = new javax.swing.JTextField();
        mn1 = new javax.swing.JTextField();
        m12 = new javax.swing.JTextField();
        m14 = new javax.swing.JTextField();
        mn3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        na3 = new javax.swing.JTextField();
        na2 = new javax.swing.JTextField();
        na4 = new javax.swing.JTextField();
        add3 = new javax.swing.JTextField();
        pn2 = new javax.swing.JTextField();
        pn4 = new javax.swing.JTextField();
        add4 = new javax.swing.JTextField();
        add1 = new javax.swing.JTextField();
        na1 = new javax.swing.JTextField();
        pn1 = new javax.swing.JTextField();
        add2 = new javax.swing.JTextField();
        pn3 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        DOJ4 = new javax.swing.JTextField();
        dg1 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        dg3 = new javax.swing.JTextField();
        ph3 = new javax.swing.JTextField();
        ph2 = new javax.swing.JTextField();
        ph4 = new javax.swing.JTextField();
        dg4 = new javax.swing.JTextField();
        DOJ2 = new javax.swing.JTextField();
        dg2 = new javax.swing.JTextField();
        DOJ1 = new javax.swing.JTextField();
        d4 = new javax.swing.JTextField();
        ph1 = new javax.swing.JTextField();
        d3 = new javax.swing.JTextField();
        DOJ3 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.black), "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jButton1.setText("CREATE TABLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Reteive");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(s4)
                            .addComponent(s3)
                            .addComponent(s2)
                            .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.black), "Existing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel1.setText("database name");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray), "Appointment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jButton4.setText("Create Table");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Insert");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Retrive");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(an1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(an2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(an3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(an4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aa2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aa3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aa4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(at4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(at3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(at2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(at1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ad1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(ad2)
                            .addComponent(ad3)
                            .addComponent(ad4)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(at1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(at2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(at3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(an1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(aa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(an2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(an3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(an4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(aa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(at4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(aa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton5))
                    .addComponent(jButton6))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102)), "Medicine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel4.setInheritsPopupMenu(true);

        m11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m11ActionPerformed(evt);
            }
        });

        jButton7.setText("Create Table");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Insert");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Retrive");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mn4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton7)))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m33, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m32, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m34, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(mn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(mn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(m22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(mn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(mn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(m13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(m14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(m24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(m31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(m32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(m33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(m23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addComponent(m34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7)
                        .addComponent(jButton8))
                    .addComponent(jButton9))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)), "Patient Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jButton10.setText("Create Table");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Insert");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Retrive");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(na3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(na2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(na1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(na4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pn3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11)))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(na1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(na2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(na3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(na4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(add3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(add4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton10)
                        .addComponent(jButton11))
                    .addComponent(jButton12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)), "Doctor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        dg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dg3ActionPerformed(evt);
            }
        });

        ph2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ph2ActionPerformed(evt);
            }
        });

        ph4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ph4ActionPerformed(evt);
            }
        });

        dg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dg4ActionPerformed(evt);
            }
        });

        d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ActionPerformed(evt);
            }
        });

        ph1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ph1ActionPerformed(evt);
            }
        });

        jButton13.setText("Table");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Insert");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Retrive");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DOJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOJ3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOJ4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(dg4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ph4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(dg3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ph3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(dg2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ph2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(dg1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ph1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jButton15)))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addGap(49, 49, 49)
                        .addComponent(jButton14)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(DOJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DOJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(DOJ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DOJ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(d4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(ph1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ph2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ph3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ph4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton14)
                        .addComponent(jButton13))
                    .addComponent(jButton15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
     String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

        Connection con= null;
        Statement stm =null;
       
        try {
             Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
              stm= (Statement) con.createStatement();
            String sql ="Create table status(n1 VARCHAR(100),n2 VARCHAR(100),n3 VARCHAR(100),n4 VARCHAR(100),s1 VARCHAR(100),s2 VARCHAR(100),s3 VARCHAR(100),s4 VARCHAR(100));";   
            stm.executeUpdate(sql);
            
            
               JOptionPane.showMessageDialog(this,"Create Table....... ");
               
        
               
                stm.close();
                con.close();
        } catch (Exception e) {
            
            System.out.println("ERROR: " + e.getMessage());
        }
   
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
     String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

        Connection con= null;
        Statement stm =null;
       
        try {
             Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
              stm= (Statement) con.createStatement();
            String sql ="INSERT INTO `status`(`n1`, `n2`, `n3`, `n4`, `s1`, `s2`, `s3`, `s4`) VALUES ('"+n1.getText()+"','"+n2.getText()+"','"+n3.getText()+"','"+n4.getText()+"','"+v1.getText()+"','"+s2.getText()+"','"+s3.getText()+"','"+s4.getText()+"')";   
            stm.executeUpdate(sql);
            
            
               JOptionPane.showMessageDialog(this,"Create Table....... ");
               
        
               
                stm.close();
                con.close();
        } catch (Exception e) {
            
            System.out.println("ERROR: " + e.getMessage());
        }
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
     String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

       
        Connection con= null;
        Statement stm =null;
         try {
                Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
             stm= (Statement) con.createStatement();
             
              String query= "SELECT * FROM status;";
              
              
             ResultSet rs= stm.executeQuery(query);
              
            while(rs.next())
            {
                String a1 = rs.getString("n1");
                String a2  = rs.getString("n2");
                 String a3 = rs.getString("n3");
                String a4 = rs.getString("n4");
                 String a5 = rs.getString("s1");
                String a6 = rs.getString("s2");
                String a7 = rs.getString("s3");
                 String a8 = rs.getString("s4");
           // asd.chat.setText(s1);
           
         
            
        n1.setText(a1);
       n2.setText(a2);
        n3.setText(a3);
         n4.setText(a4);
         v1.setText(a5);
         s2.setText(a6);
         s3.setText(a7);
         s4.setText(a8);
            }
        
              stm.close();
            con.close();
            rs.close();
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,  e.getMessage() );
            
            
        }
        
        
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

        Connection con= null;
        Statement stm =null;
       
        try {
             Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
              stm= (Statement) con.createStatement();
            String sql ="Create table app(an1 VARCHAR(100),an2 VARCHAR(100),an3 VARCHAR(100),an4 VARCHAR(100),aa1 DATE,aa2 DATE,aa3 DATE,aa4 DATE,at1 TIME,at2 TIME,at3 TIME,at4 TIME,ad1 VARCHAR(30),ad2 VARCHAR(20),ad3 VARCHAR(20),ad4 VARCHAR(20));";   
            stm.executeUpdate(sql);
            
            
               JOptionPane.showMessageDialog(this,"Create Table....... ");
        
               
                stm.close();
                con.close();
        } catch (Exception e) {
            
          JOptionPane.showMessageDialog(this,"ERROR: " + e.getMessage());
        }
   
    }                                        

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
          String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

        Connection con= null;
        Statement stm =null;
       
        try {
             Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
              stm= (Statement) con.createStatement();
            String sql ="INSERT INTO `app`(`an1`, `an2`, `an3`, `an4`, `aa1`, `aa2`, `aa3`, `aa4`, `at1`, `at2`, `at3`, `at4`,`ad1`, `ad2`, `ad3`, `ad4`) VALUES ('"+an1.getText()+"','"+an2.getText()+"','"+an3.getText()+"','"+an4.getText()+"','"+aa1.getText()+"','"+aa2.getText()+"','"+aa3.getText()+"','"+aa4.getText()+"','"+ad1.getText()+"','"+ad2.getText()+"','"+ad3.getText()+"','"+ad4.getText()+"')";   
            stm.executeUpdate(sql);
            
            
               JOptionPane.showMessageDialog(this,"Insert Table....... ");
               
        
               
                stm.close();
                con.close();
        } catch (Exception e) {
            
            System.out.println("ERROR: " + e.getMessage());
        }
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

       
        Connection con= null;
        Statement stm =null;
         try {
                Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
             stm= (Statement) con.createStatement();
             
              String query= "SELECT * FROM app;";
              
              
             ResultSet rs= stm.executeQuery(query);
              
            while(rs.next())
            {
                String a1 = rs.getString("an1");
                String a2  = rs.getString("an2");
                 String a3 = rs.getString("an3");
                String a4 = rs.getString("an4");
                 String a5 = rs.getString("aa1");
                String a6 = rs.getString("aa2");
                String a7 = rs.getString("aa3");
                 String a8 = rs.getString("aa4");
                 String a9 = rs.getString("at1");
                String a10 = rs.getString("at2");
                String a11 = rs.getString("at3");
                 String a12 = rs.getString("at4");
                  String a13 = rs.getString("ad1");
                String a14 = rs.getString("ad2");
                String a15 = rs.getString("ad3");
                 String a16 = rs.getString("ad4");
           // asd.chat.setText(s1);
           
         
            
        an1.setText(a1);
       an2.setText(a2);
        an3.setText(a3);
         an4.setText(a4);
         aa1.setText(a5);
         aa2.setText(a6);
         aa3.setText(a7);
         aa4.setText(a8);
         at1.setText(a9);
         at2.setText(a10);
         at3.setText(a11);
         at4.setText(a12);
         ad1.setText(a13);
         ad2.setText(a14);
         ad3.setText(a15);
         ad4.setText(a16);
            }
        
              stm.close();
            con.close();
            rs.close();
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,  e.getMessage() );
            
            
        }
        
    }                                        

    private void m11ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
     String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

        Connection con= null;
        Statement stm =null;
       
        try {
             Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
              stm= (Statement) con.createStatement();
            String sql ="Create table medicine(mn1 VARCHAR(20),mn2 VARCHAR(20),mn3 VARCHAR(20),mn4 VARCHAR(20),m11 VARCHAR(20),m12 VARCHAR(20),m13 VARCHAR(20),m14 VARCHAR(20),m21 VARCHAR(20),m22 VARCHAR(20),m23 VARCHAR(20),m24 VARCHAR(20),m31 VARCHAR(20),m32 VARCHAR(20),m33 VARCHAR(20),m34 VARCHAR(20),Sm41 VARCHAR(20),m42 VARCHAR(20),m43 VARCHAR(20),m44 VARCHAR(20));";   
            stm.executeUpdate(sql);
            
            
               JOptionPane.showMessageDialog(this,"Create Table....... ");
               
        
               
                stm.close();
                con.close();
        } catch (Exception e) {
            
            System.out.println("ERROR: " + e.getMessage());
        }
   
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

        Connection con= null;
        Statement stm =null;
       
        try {
             Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
              stm= (Statement) con.createStatement();
            String sql ="','"+"INSERT INTO `medicine`(`mn1`, `mn2`, `mn3`, `mn4`, `m11`, `m12`, `m13`, `m14`, `m21`, `m22`, `m23`, `m24`, `m41`, `m42`, `m43`, `m44`) VALUES ('"+mn1.getText()+"','"+mn2.getText()+"','"+mn3.getText()+"','"+mn4.getText()+"','"+m11.getText()+"','"+m12.getText()+"','"+m13.getText()+"','"+m14.getText()+"','"+m21.getText()+"','"+m22.getText()+"','"+m23.getText()+"','"+m24.getText()+"','"+m31.getText()+"','"+m32.getText()+"','"+m33.getText()+"','"+m34.getText()+"');";   
            stm.executeUpdate(sql);
            
            
               JOptionPane.showMessageDialog(this,"Create Table....... ");
               
        
               
                stm.close();
                con.close();
        } catch (Exception e) {
            
            System.out.println("ERROR: " + e.getMessage());
        }
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

       
        Connection con= null;
        Statement stm =null;
         try {
                Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
             stm= (Statement) con.createStatement();
             
              String query= "SELECT * FROM Medicine;";
              
              
             ResultSet rs= stm.executeQuery(query);
              
            while(rs.next())
            {
                String a1 = rs.getString("mn1");
                String a2  = rs.getString("mn2");
                String a3 = rs.getString("mn3");
                String a4 = rs.getString("mn4");
                String a5 = rs.getString("m11");
                String a6 = rs.getString("m12");
                String a7 = rs.getString("m13");
                String a8 = rs.getString("m14");
                String a9 = rs.getString("m21");
                String a10 = rs.getString("m22");
                String a11 = rs.getString("m23");
                String a12 = rs.getString("m24");
                 String a13 = rs.getString("m41");
                String a14 = rs.getString("m42");
                String a15 = rs.getString("m43");
                String a16 = rs.getString("m44");
              
               
                
           // asd.chat.setText(s1);
           
         
            
        mn1.setText(a1);
       mn2.setText(a2);
        mn3.setText(a3);
         mn4.setText(a4);
         m11.setText(a5);
         m12.setText(a6);
         m13.setText(a7);
         m14.setText(a8);
         m21.setText(a9);
         m22.setText(a10);
         m23.setText(a11);
         m24.setText(a12);
         m31.setText(a13);
         m32.setText(a14);
         m33.setText(a15);
         m34.setText(a16);
            }
        
              stm.close();
            con.close();
            rs.close();
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,  e.getMessage() );
            
            
        }

    }                                        

    private void d4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void dg3ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void dg4ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void ph4ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void ph2ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void ph1ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

        Connection con= null;
        Statement stm =null;
       
        try {
             Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
              stm= (Statement) con.createStatement();
            String sql ="INSERT INTO `patientd`(`na1`, `na2`, `na3`, `na4`, `pn1`, `pn2`, `pn3`, `pn4`, `add1`, `add2`, `add3`, `add4`) VALUES ([value-1],[value-2],[value-3],[value-4],[value-5],[value-6],[value-7],[value-8],[value-9],[value-10],[value-11],[value-12]),)";   
            stm.executeUpdate(sql);
            
            
               JOptionPane.showMessageDialog(this,"Insert Table....... ");
               
        
               
                stm.close();
                con.close();
        } catch (Exception e) {
            
            System.out.println("ERROR: " + e.getMessage());
        }
    }                                   

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
           String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

        Connection con= null;
        Statement stm =null;
       
        try {
             Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
              stm= (Statement) con.createStatement();
            String sql ="Create table patientd(na1 VARCHAR(100),na2 VARCHAR(100),na3 VARCHAR(100),na4 VARCHAR(100),pn1 VARCHAR(100),pn2 VARCHAR(100),pn3 VARCHAR(100),pn4 VARCHAR(100),add1 VARCHAR(100),add2 VARCHAR(100),add3 VARCHAR(100),add4 VARCHAR(100));";   
            stm.executeUpdate(sql);
            
               JOptionPane.showMessageDialog(this,"Create Table....... ");
               
                stm.close();
                con.close();
        } catch (Exception e) {
            
            System.out.println("ERROR: " + e.getMessage());
        }
   
    }                                         

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

        Connection con= null;
        Statement stm =null;
       
        try {
             Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
              stm= (Statement) con.createStatement();
            String sql ="INSERT INTO `patientd`(`na1`, `na2`, `na3`, `na4`, `pn1`, `pn2`, `pn3`, `pn4`, `add1`, `add2`, `add3`, `add4`) VALUES ('"+na1.getText()+"','"+na2.getText()+"','"+na3.getText()+"','"+na4.getText()+"','"+pn1.getText()+"','"+pn2.getText()+"','"+pn3.getText()+"','"+pn4.getText()+"','"+add1.getText()+"','"+add2.getText()+"','"+add3.getText()+"','"+add3.getText()+"'))";   
            stm.executeUpdate(sql);
            
            
               JOptionPane.showMessageDialog(this,"Insert Table....... ");
               
        
               
                stm.close();
                con.close();
        } catch (Exception e) {
            
            System.out.println("ERROR: " + e.getMessage());
        }
    }                                         

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
       String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

       
        Connection con= null;
        Statement stm =null;
         try {
                Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
             stm= (Statement) con.createStatement();
             
              String query= "SELECT * FROM patientd;";
              
              
             ResultSet rs= stm.executeQuery(query);
              
            while(rs.next())
            {
                String a1 = rs.getString("na1");
                String a2  = rs.getString("na2");
                 String a3 = rs.getString("na3");
                String a4 = rs.getString("na4");
                 String a5 = rs.getString("pn1");
                String a6 = rs.getString("pn2");
                String a7 = rs.getString("pn3");
                 String a8 = rs.getString("pn4");
                 String a9 = rs.getString("add1");
                String a10 = rs.getString("add2");
                String a11 = rs.getString("add3");
                 String a12 = rs.getString("add4");
                
           // asd.chat.setText(s1);
           
         
            
        na1.setText(a1);
       na2.setText(a2);
        na3.setText(a3);
         na4.setText(a4);
         pn1.setText(a5);
         pn2.setText(a6);
         pn3.setText(a7);
         pn4.setText(a8);
         add1.setText(a9);
         add2.setText(a10);
         add3.setText(a11);
         add4.setText(a12);
        
            }
        
              stm.close();
            con.close();
            rs.close();
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,  e.getMessage() );
            
            
        }
     
    }                                         

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
           String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

        Connection con= null;
        Statement stm =null;
       
        try {
             Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
              stm= (Statement) con.createStatement();
            String sql ="Create table doc(d1 VARCHAR(100),d2 VARCHAR(100),d3 VARCHAR(100),d4 VARCHAR(100),DOJ1 DATE,DOJ2 DATE,DOJ3 DATE,DOJ4 DATE,dg1 VARCHAR(100),dg2 VARCHAR(100),dg3 VARCHAR(100),dg4 VARCHAR(100),pn1 VARCHAR(100),pn2 VARCHAR(100),pn3 VARCHAR(100),pn4 VARCHAR(100));";   
            stm.executeUpdate(sql);
            
               JOptionPane.showMessageDialog(this,"Create Table....... ");
               
                stm.close();
                con.close();
        } catch (Exception e) {
            
            System.out.println("ERROR: " + e.getMessage());
        }
   
    }                                         

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
     String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

        Connection con= null;
        Statement stm =null;
       
        try {
             Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
              stm= (Statement) con.createStatement();
            String sql ="INSERT INTO `patientdo`(`d1`, `d2`, `d3`, `d4`, `DOJ1`, `DOJ2`, `DOJ3`, `DOJ4`, `dg1`, `dg2`, `dg3`, `dg4`, `pn1`, `pn2`, `pn3`, `pn4`) VALUES ('"+d1.getText()+"','"+d2.getText()+"','"+d3.getText()+"','"+d4.getText()+"','"+DOJ1.getText()+"','"+DOJ2.getText()+"','"+DOJ3.getText()+"','"+DOJ4.getText()+"','"+dg1.getText()+"','"+dg2.getText()+"','"+dg3.getText()+"','"+dg4.getText()+"','"+ph1.getText()+"','"+ph2.getText()+"','"+ph3.getText()+"','"+ph4.getText()+"'))";   
            stm.executeUpdate(sql);
            
            
               JOptionPane.showMessageDialog(this,"Insert Table....... ");
               
        
               
                stm.close();
                con.close();
        } catch (Exception e) {
            
            System.out.println("ERROR: " + e.getMessage());
        }
    }                                         

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
    String s1=name.getText();
            String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/"+s1+"";
      String DB_USER ="root";
       String DB_PASS ="";

       
        Connection con= null;
        Statement stm =null;
         try {
                Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
             stm= (Statement) con.createStatement();
             
              String query= "SELECT * FROM doc;";
              
              
             ResultSet rs= stm.executeQuery(query);
              
            while(rs.next())
            {
                String a1 = rs.getString("d1");
                String a2  = rs.getString("d2");
                 String a3 = rs.getString("d3");
                String a4 = rs.getString("d4");
                String a5 = rs.getString("DOJ1");
                String a6 = rs.getString("DOJ2");
                String a7 = rs.getString("DOJ3");
                 String a8 = rs.getString("DOJ4");
                 String a9 = rs.getString("dg1");
                String a10 = rs.getString("dg2");
                String a11 = rs.getString("dg3");
                 String a12 = rs.getString("dg4");
                 String a13 = rs.getString("pn1");
                String a14 = rs.getString("pn2");
                String a15 = rs.getString("pn3");
                 String a16 = rs.getString("pn4");
                
           // asd.chat.setText(s1);
           
         
            
        d1.setText(a1);
       d2.setText(a2);
        d3.setText(a3);
         d4.setText(a4);
         DOJ1.setText(a5);
         DOJ2.setText(a6);
         DOJ3.setText(a7);
         DOJ4.setText(a8);
         dg1.setText(a9);
         dg2.setText(a10);
         dg3.setText(a11);
         dg4.setText(a12);
          ph1.setText(a13);
         ph2.setText(a14);
         ph3.setText(a15);
         ph4.setText(a16);
        
            }
        
              stm.close();
            con.close();
            rs.close();
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,  e.getMessage() );
            
            
        }
     
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managedata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managedata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField DOJ1;
    private javax.swing.JTextField DOJ2;
    private javax.swing.JTextField DOJ3;
    private javax.swing.JTextField DOJ4;
    private javax.swing.JTextField aa1;
    private javax.swing.JTextField aa2;
    private javax.swing.JTextField aa3;
    private javax.swing.JTextField aa4;
    private javax.swing.JTextField ad1;
    private javax.swing.JTextField ad2;
    private javax.swing.JTextField ad3;
    private javax.swing.JTextField ad4;
    private javax.swing.JTextField add1;
    private javax.swing.JTextField add2;
    private javax.swing.JTextField add3;
    private javax.swing.JTextField add4;
    private javax.swing.JTextField an1;
    private javax.swing.JTextField an2;
    private javax.swing.JTextField an3;
    private javax.swing.JTextField an4;
    private javax.swing.JTextField at1;
    private javax.swing.JTextField at2;
    private javax.swing.JTextField at3;
    private javax.swing.JTextField at4;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField d3;
    private javax.swing.JTextField d4;
    private javax.swing.JTextField dg1;
    private javax.swing.JTextField dg2;
    private javax.swing.JTextField dg3;
    private javax.swing.JTextField dg4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField m11;
    private javax.swing.JTextField m12;
    private javax.swing.JTextField m13;
    private javax.swing.JTextField m14;
    private javax.swing.JTextField m21;
    private javax.swing.JTextField m22;
    private javax.swing.JTextField m23;
    private javax.swing.JTextField m24;
    private javax.swing.JTextField m31;
    private javax.swing.JTextField m32;
    private javax.swing.JTextField m33;
    private javax.swing.JTextField m34;
    private javax.swing.JTextField mn1;
    private javax.swing.JTextField mn2;
    private javax.swing.JTextField mn3;
    private javax.swing.JTextField mn4;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField n4;
    private javax.swing.JTextField na1;
    private javax.swing.JTextField na2;
    private javax.swing.JTextField na3;
    private javax.swing.JTextField na4;
    private javax.swing.JTextField name;
    private javax.swing.JTextField ph1;
    private javax.swing.JTextField ph2;
    private javax.swing.JTextField ph3;
    private javax.swing.JTextField ph4;
    private javax.swing.JTextField pn1;
    private javax.swing.JTextField pn2;
    private javax.swing.JTextField pn3;
    private javax.swing.JTextField pn4;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JTextField v1;
    // End of variables declaration                   
}
