/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import static frame.Patient.main;
import java.awt.PopupMenu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Saurav
 */
public class Doctor extends javax.swing.JFrame {
    private Object jTextField1;
    private Object App;
    private Object jPasswordField1;

    /**
     * Creates new form Doctor
     */
    public Doctor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
   Appointment ap=new Appointment();
 DoctorD dd=new DoctorD();
   Details pd=new Details();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(690, 0, 60, 50);

        jButton2.setText("Click To See Second Page");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(520, 420, 200, 23);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(580, 60, 130, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(580, 110, 130, 30);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-checklist-filled-50.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Patients");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(80, 250, 160, 130);

        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-calendar-50.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Appointments");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(31, 31, 31))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(25, 25, 25))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(500, 250, 150, 130);

        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-stethoscope-filled-50.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Doctor Details");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(290, 250, 148, 130);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(590, 160, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("User Name ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 70, 130, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(470, 120, 130, 22);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Saurav\\Desktop\\pr\\AdobeStock_65704664-805x503.jpeg")); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, -6, 750, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {                                     


    }                                    

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {                                     
String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/hospital2";
      String DB_USER ="root";
       String DB_PASS ="";

       
        Connection con= null;
        Statement stm =null;
         try {
                Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
             stm= (Statement) con.createStatement();
             
              String query= "SELECT * FROM patientd;";
              
              
             ResultSet rs= stm.executeQuery(query);
              
            while(rs.next())
            {
                String a1 = rs.getString("na1");
                String a2  = rs.getString("na2");
                 String a3 = rs.getString("na3");
                String a4 = rs.getString("na4");
                 String a5 = rs.getString("pn1");
                String a6 = rs.getString("pn2");
                String a7 = rs.getString("pn3");
                 String a8 = rs.getString("pn4");
                 String a9 = rs.getString("add1");
                String a10 = rs.getString("add2");
                String a11 = rs.getString("add3");
                 String a12 = rs.getString("add4");
                
           // asd.chat.setText(s1);
           
        pd.setVisible(true);
             
         pd.na1.setText(a1);
         pd.na2.setText(a2);
         pd.na3.setText(a3);
         pd.na4.setText(a4);
         pd.pn1.setText(a5);
         pd.pn2.setText(a6);
         pd.pn3.setText(a7);
         pd.pn4.setText(a8);
         pd.add1.setText(a9);
         pd.add2.setText(a10);
         pd.add3.setText(a11);
         pd.add4.setText(a12);
        
            }
        
              stm.close();
            con.close();
            rs.close();
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,  e.getMessage() );
            
            
        }         
    }                                    

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {                                     
String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/hospital2";
      String DB_USER ="root";
       String DB_PASS ="";

       
        Connection con= null;
        Statement stm =null;
         try {
                Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
             stm= (Statement) con.createStatement();
             
              String query= "SELECT * FROM app;";
              
              
             ResultSet rs= stm.executeQuery(query);
              
            while(rs.next())
            {
                String a1 = rs.getString("an1");
                String a2  = rs.getString("an2");
                 String a3 = rs.getString("an3");
                String a4 = rs.getString("an4");
                 String a5 = rs.getString("aa1");
                String a6 = rs.getString("aa2");
                String a7 = rs.getString("aa3");
                 String a8 = rs.getString("aa4");
                 String a9 = rs.getString("at1");
                String a10 = rs.getString("at2");
                String a11 = rs.getString("at3");
                 String a12 = rs.getString("at4");
                 String a13 = rs.getString("ad1");
                String a14 = rs.getString("ad2");
                String a15 = rs.getString("ad3");
                 String a16 = rs.getString("ad4");
           // asd.chat.setText(s1);
           
        ap.setVisible(true);
             
            
         ap.an1.setText(a1);
         ap.an2.setText(a2);
         ap. an3.setText(a3);
         ap.an4.setText(a4);
         ap.aa1.setText(a5);
         ap.aa2.setText(a6);
         ap.aa3.setText(a7);
         ap.aa4.setText(a8);
         ap.at1.setText(a9);
         ap.at2.setText(a10);
         ap.at3.setText(a11);
         ap.at4.setText(a12);
        
        
         
           
            }
        
              stm.close();
            con.close();
            rs.close();
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,  e.getMessage() );
            
            
        }        
           
    }                                    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
   String us=jTextField3.getText();
   String pas=jTextField2.getText();
        if(us.equals("admin") && pas.equals("1234"))
       
        if (!us.equals("admin"))
        {
            JOptionPane.showMessageDialog(this, "Some is Wrong with userName");
           if (! pas.equals("1234"))
         
        {
            JOptionPane.showMessageDialog(this, "Some thing is wrong with password");
        }
        }
          if (! pas.equals("1234"))
          {
              JOptionPane.showMessageDialog(this, "Some thing is wrong with password");
          }
        
               

    }                                        

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {                                     
        String JDBC_DRIVER ="com.mysql.jdbc.Driver";
        String DB_URL ="jdbc:mysql://localhost/hospital2";
      String DB_USER ="root";
       String DB_PASS ="";

       
        Connection con= null;
        Statement stm =null;
         try {
                Class.forName(JDBC_DRIVER);
              con = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASS);
             stm= (Statement) con.createStatement();
             
              String query= "SELECT * FROM doc;";
              
              
             ResultSet rs= stm.executeQuery(query);
              
            while(rs.next())
            {
                String a1 = rs.getString("d1");
                String a2  = rs.getString("d2");
                 String a3 = rs.getString("d3");
                String a4 = rs.getString("d4");
                 String a5 = rs.getString("DOJ1");
                String a6 = rs.getString("DOJ2");
                String a7 = rs.getString("DOJ3");
                 String a8 = rs.getString("DOJ4");
                 String a9 = rs.getString("dg1");
                String a10 = rs.getString("dg2");
                String a11 = rs.getString("dg3");
                 String a12 = rs.getString("dg4");
                 String a13 = rs.getString("pn1");
                String a14 = rs.getString("pn2");
                String a15 = rs.getString("pn3");
                 String a16 = rs.getString("pn4");
                
           // asd.chat.setText(s1);
           
        dd.setVisible(true);
             
         dd.d1.setText(a1);
         dd.d2.setText(a2);
         dd.d3.setText(a3);
         dd.d4.setText(a4);
         dd.DOJ1.setText(a5);
         dd.DOJ2.setText(a6);
         dd.DOJ3.setText(a7);
         dd.DOJ4.setText(a8);
         dd.dg1.setText(a9);
         dd.dg2.setText(a10);
         dd.dg3.setText(a11);
         dd.dg4.setText(a12);
          dd.pn1.setText(a13);
         dd.pn2.setText(a14);
         dd.pn3.setText(a15);
         dd.pn4.setText(a16);
        
            }
        
              stm.close();
            con.close();
            rs.close();
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this,  e.getMessage() );
            
            
        }         

    }                                    

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    new Patient().setVisible(true);
            this.setVisible(false);
    }                                        

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    System.exit(0);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration                   

    static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
